f3_final/urls.py
from django.conf.urls.defaults import patterns, url, include
from django.views.generic import list_detail
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

import views

urlpatterns = patterns( '',
                       url( r'^farm/(?P<id>\d+)/$', views.farms_detail,
                           name = "farm_detail" ),

                       url(r'^food/(?P<id>\d+)/$', views.food_detail,
                           name="food_detail"),

                       url( r'^json/all',
                           "f3_final.views.farm_json_all" ),

                       url( r'^$', views.index, name = "index" ),
                       #url( r'^admin/', include( admin.site.urls ) )

                       )

# Django's static file server is inefficient and insecure
# for production use, serve these files via Apache or (better) Nginx
if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
 )

urls.py
from django.conf.urls.defaults import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

import f3_final.views

urlpatterns = patterns('',


                       # dispatch to the urls for f3_final
                       (r'^f3/', include('f3_final.urls')),

                       # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
                       # to INSTALLED_APPS to enable admin documentation:
                       # (r'^admin/doc/', include('django.contrib.admindocs.urls')),
                       
                       # Uncomment the next line to enable the admin:
                       (r'^admin/', include(admin.site.urls)),
                       )

f3_final/models.py
import django.db.models as m


class Farm(m.Model):

    name = m.CharField(max_length=100)
    contact_person = m.CharField(max_length=100)
    address = m.TextField()
    latitude = m.FloatField(null=True,blank=True)
    longitude = m.FloatField(null=True,blank=True)
    phone_number = m.CharField(max_length=30)
    website = m.URLField(blank=True)
    email_address = m.EmailField(blank=True)
    description = m.TextField(blank=True)
    hours_of_operation = m.CharField(max_length=100,blank=True)
    seasonal_operation = m.CharField(max_length=100,blank=True)
    service_offerings = m.ManyToManyField('ServiceOffering',blank=True)
    payment_methods = m.ManyToManyField('PaymentMethod',blank=True)
    sustainability_indicators = m.ManyToManyField('SustainabilityIndicator',blank=True)
    categories = m.ManyToManyField('FarmCategory',blank=True)
    confirmed_foods = m.ManyToManyField('Food',blank=True)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/f3/farms/%s/" % self.id

    def get_service_offerings(self):
        service_list = []
        for service in self.service_offerings.all():
            service_list.append(service.name)
        return service_list

    def acceptscreditcards(self):
        if self.payment_methods.all():
            for payment in self.payment_methods.all():
                if payment.name in ["Visa","MC"]:
                    return True

    def displaydescription(self):
        return "Located at:" + self.address or '???'

    class Meta:
        ordering = ["name"]


class FarmCategory(m.Model):

    name = m.CharField(max_length=50)
    foods = m.ManyToManyField('Food')

    class Meta:
        verbose_name_plural = 'farm categories'

    def __unicode__(self):
        return self.name


class Food(m.Model):
    """Some food that grows on a farm."""

    name = m.CharField(max_length=50,
                       unique=True,
                       help_text="the name of the food")
    type = m.ForeignKey('FoodType')
    months = m.ManyToManyField('Month')
    description = m.TextField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return "/f3/food/%s/" % self.name

    def displaydescription(self):
        return self.type

    class Meta:
        ordering = ["name"]


class FoodType(m.Model):

    name = m.CharField(max_length=30, unique=True)

    def __unicode__(self):
        return self.name


class Month(m.Model):
    """The months"""

    name = m.CharField(max_length=10,
                       unique=True,
                       help_text="the month")
    order = m.IntegerField(unique=True)

    def __unicode__(self):
        return self.name


class PaymentMethod(m.Model):
    """How you can pay for the food. Includes a 'null value' of
    Unspecified, since we expect our knowledge is incomplete."""
    name = m.CharField(max_length=50, unique=True)

    def __unicode__(self):
        return self.name


class ServiceOffering(m.Model):
    """Services offered by a Farm (e.g. U-Pick, Phone Orders)"""
    name = m.CharField(max_length=50, unique=True)
    description = m.TextField(blank=True)

    def __unicode__(self):
        return self.name


class SustainabilityIndicator(m.Model):
    """Commitments by a Farm to sustainability. Represented by an icon
    in the paper guide. There are likely some inter-relationships here
    we're not modeling."""
    name = m.CharField(max_length=50, unique=True)
    description = m.TextField()
    filename_base = m.CharField(max_length=50)

    def __unicode__(self):
        return self.name

f3_final/views.py
import datetime, calendar

try:
    import json
except ImportError:
    import simplejson as json

from django.http import HttpResponse
from django.shortcuts import render_to_response, get_object_or_404, get_list_or_404
from django.template import RequestContext
from django.template.loader import get_template
import f3_final.models as models

named_month = lambda month_num:calendar.month_name[month_num]

def index( request ):
    return render_to_response( "index.html",
                              {}, context_instance = RequestContext(
                                request
                              )
                            )


def farms_list( request ):
    obj_list = models.Farm.objects.all()
    return render_to_response( 'object_list.html',
                               {'object_list': obj_list,
                                'object_type': 'Farm',
                                }, context_instance = RequestContext( request ) )


def farms_detail( request, id ):
    obj = get_object_or_404( models.Farm, id = id )
    return render_to_response( 'farm_detail.html',
                               {'object':obj,
                                'object_type':'Farm',
                                },context_instance=RequestContext(request))


def food_detail(request, id):
    food = models.Food.objects.get(id=id)
    farmsWithFood = models.Farm.objects.filter(confirmed_foods=food)
    return render_to_response('food_detail.html',
                               context_instance=RequestContext(request, {'food': food, 'farmsWithFood': farmsWithFood}))


def farms_with_food( request, food_id ):
    obj_list = get_list_or_404(models.Farm, confirmed_foods=food_id)
    restr = ' (with %s)' % models.Food.objects.get(id=food_id).name
    return render_to_response( 'object_list.html',
                              {'object_list': obj_list,
                               'object_type': 'Farm',
                               'restriction': restr,
                               }, context_instance = RequestContext( request ) )

def farm_json_all( request ):
    return HttpResponse(
                        json.dumps(
                                   [
                                       [
                                        farm.name,
                                        [
                                         farm.latitude,
                                         farm.longitude
                                        ]
                                       ]
                                      for farm in models.Farm.objects.all()
                                    ],
                                    indent = 4,
                                    sort_keys = True
                                )
                            )

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ title }}</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/combo?2.8.2r1/build/reset-fonts-grids/reset-fonts-grids.css&amp;2.8.2r1/build/base/base-min.css">
    <link rel="stylesheet" type="text/css" href="/f3/media/css/base.css">

    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.2/jquery.min.js"></script>
    <script type="text/javascript" src="/f3/media/js/equalColumns.js"></script>
    <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
    <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
    <script type="text/javascript" src="/f3/media/js/indexMap.js"></script>
    <script type="text/javascript" src="/f3/media/js/menuRedirect.js"></script>

</head>
<body onload="{{ onload }}">
    <div id="doc2">
        <div id="hd">
            <a href="/f3/"><img src="/f3/media/images/header.png" alt="F3 Logo"></a>
        </div>
        <div id="bd">
            <div class="yui-gf">
                <div class="yui-u first">
                    Browse by Food:
                    <br>
                    <select id="foods">
                        <option> Foods in Season</option>
                        {% for currentFood in currentFoods %}
                            <option value="{{ currentFood.id }}"> -- {{ currentFood.name }}</option>
                        {% endfor %}
                        <option>Foods not in Season (yet)</option>
                        {% for otherFood in otherFoods %}
                            <option value="{{ otherFood.id }}"> -- {{ otherFood.name }}</option>
                        {% endfor %}
                    </select>

                    <br>
                    <br>

                    Browse Farms:
                    <br>
                    <select id="farms">
                        <option>Farms</option>
                        {% for farm in farms %}
                            <option value="{{ farm.id }}"> -- {{ farm.name }}</option>
                        {% endfor %}
                    </select>
                {% block sidebar %}
                {% endblock %}
            </div>
                <div class="yui-u">
                    {%  block content %}
                        {# Stuff goes here #}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
</body>
</html>

templates/farm_detail.html
{% extends "base.html" %}

{% block content %}

    <h2>{{ object.name|capfirst }}</h2>
    <h3> Contact Information </h3>
    <ul>
        <li>
            {{ object.contact_person }}
        </li>
        <li>
            {% firstof object.address 'Address unknown' %}
        </li>
        <li>
            {{ object.phone_number }}
        </li>
        <li>
            {% firstof object.website 'No Website'%}
        </li>
    </ul>
    {% if object.food_set %}
        <h3>Foods Offered</h3>
        {% for food in object.food_set %}
            <li><a href=/f3/food/{{ food.id }}">{{ food.name }}</a></li>
        {% endfor %}
    {% endif %}
    {% if object.get_service_offerings %}
    <h3> Services Offered </h3>
    <ul>
    {% for service in object.get_service_offerings %}
        <li>
            {{ service }}
        </li>
    {% endfor %}
     </ul>
    {% endif %}

{% endblock %}

templates/food_detail.html
{% extends "base.html" %}

{% block content %}

    <h2>{{ food.name|capfirst }}</h2>
    <p>{{ food.description }}</p>
    <h3> Months Available </h3>
    <ul>
    {% for month in food.months.all %}
        <li>
            {{ month }}
        </li>
    {% endfor %}
     </ul>

    <h3>Available at Farms:</h3>
        <ul>
            {% if farmsWithFood.count < 1 %}
                <li>None</li>
            {% endif %}
                {% for farm in farmsWithFood %}
                    <li>
                        <a href="/f3/farm/{{ farm.id }}">{{ farm.name }}</a>
                    </li>
                {% endfor %}
        </ul>


{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block content %}
    <div id='map_canvas'></div>
{% endblock %}

templates/object_list.html
{% extends "base.html" %}

{% block content %}

    <h1>{{ object_type|capfirst }} List{{ restriction }}</h1>

	{% if object_list %}
	<table>
	  <thead>
		<tr><th>Name</th><th>Description</th></tr>
	  </thead>
	  <tbody>
		{% for object in object_list %}
		<tr>
		  <td><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></td>
		  <td>{{ object.displaydescription }}</td>
		</tr>
		{% endfor %}
	  </tbody>
	</table>
	{% endif %}

{% endblock %}